---
# Core router #2. Loaded explicitly with include_vars by the playbooks.
switch:
  name: "core2"
  mgmt_ip: "10.0.1.12"
  serial_number: "FDO00000002"
  role: "core_router"

  loopback0:
    ip: "10.255.255.2"
    mask: 32

  core_p2p:
    intf: "Ethernet1/1"
    ipv4: "10.0.255.0"
    mask: 31
    peer: "core1"
